[package]
name = "kas-macros"
version = "0.17.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "KAS GUI / macros"
keywords = ["gui", "proc-macro"]
categories = ["gui"]
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/kas-macros/"

[lib]
proc-macro = true

[features]
# Inject logging into macro-generated code.
# Requires that all crates using these macros depend on the log crate.
log = []

# Enable reporting of warnings from proc-macros
nightly = ["proc-macro-error3/nightly"]

# Enable pedantic warnings. These should be replaced with individual lints,
# depending on the outcome of RFC 1566 (proc macro diagnostics).
nightly-pedantic = ["nightly"]

[dependencies]
quote = "1.0"
proc-macro2 = { version = "1.0" }
proc-macro-error3 = { version = "3.0", default-features = false }
bitflags = "2.3.3"
impl-tools-lib = "0.13.0"

[dependencies.syn]
version = "3.0.2"
# We need 'extra-traits' for equality testing
# We need 'full' for parsing macros within macro arguments
features = ["extra-traits", "full", "visit", "visit-mut"]

[lints.clippy]
collapsible_if = "allow"
collapsible_else_if = "allow"
unit_arg = "allow"
redundant_pattern_matching = "allow"
